# Generated by Django 4.2.6 on 2024-12-06 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0004_alter_encyclopedia_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petapplication',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='adoption.pet'),
        ),
    ]
